import test from 'node:test';
import assert from 'node:assert/strict';
import {CasinoSession,handValue,makeDeck,pokerResult} from '../src/casino.js';
import {CASINO_BUILDING,BUILDING_PORTALS,CASINO_FIXTURES,canWalk,nearestPortal,portalDestination,casinoActivityAt} from '../src/world.js';
const c=(rank,suit='♠')=>({rank,suit});
const session=(rng=()=>.2)=>new CasinoSession(rng,{coins:100});
function fixed(s,cards,dealer,deck,bet=10){s.balance-=bet;s.hand={player:cards,dealer,deck,bet,active:0,hands:[{cards,bet,status:'playing',split:false}],status:'playing',payout:0};}
test('casino has solid walls/furniture, reachable activities, and a return passage',()=>{const p=BUILDING_PORTALS[0];for(const layer of ['surface','casino']){assert.ok(canWalk(p[layer].x,p[layer].y,layer));assert.equal(nearestPortal(p[layer].x,p[layer].y,layer).id,p.id);}assert.equal(portalDestination(p,'surface'),'casino');assert.equal(canWalk(CASINO_BUILDING.x,CASINO_BUILDING.y,'surface'),false);for(const f of CASINO_FIXTURES){assert.equal(canWalk(f.x,f.y,'casino'),false);assert.ok(canWalk(f.activity.x,f.activity.y,'casino'));assert.equal(casinoActivityAt(f.activity.x,f.activity.y).id,f.id);}});
test('slots spend the shared wallet and cannot mint refills or spend unavailable coins',()=>{const wallet={coins:100},s=new CasinoSession(()=>0,wallet);assert.equal(s.spin(10).payout,40);assert.equal(wallet.coins,130);wallet.coins=0;assert.throws(()=>s.spin(10),/Not enough coins/);assert.equal(typeof s.refill,'undefined');assert.equal(new CasinoSession().balance,0);});
test('six-deck shoe, soft aces, and natural blackjack settlement are correct',()=>{assert.equal(makeDeck(()=>.3,6).length,312);assert.equal(makeDeck(()=>.3).length,52);assert.equal(handValue([c('A'),c('A'),c('9')]),21);const s=session();fixed(s,[c('A'),c('K')],[c('9'),c('8')],[]);s.checkBlackjack();assert.equal(s.balance,115);s.settle(25,'again');assert.equal(s.balance,115);const t=session();fixed(t,[c('A'),c('K')],[c('A'),c('Q')],[]);t.checkBlackjack();assert.equal(t.balance,100);});
test('dealer stands on soft 17, ordinary wins pay 1:1, pushes return the wager, busts lose',()=>{const s=session();fixed(s,[c('10'),c('7')],[c('A'),c('6')],[c('K')]);s.stand();assert.equal(s.hand.dealer.length,2);assert.equal(s.balance,100);fixed(s,[c('K'),c('9')],[c('10'),c('8')],[]);s.stand();assert.equal(s.balance,110);fixed(s,[c('K'),c('Q')],[c('10'),c('8')],[c('2')]);s.hit();assert.equal(s.hand.status,'finished');assert.equal(s.balance,100);});
test('split hands play independently; split 21 pays even money and multiple hands settle once',()=>{const s=session();fixed(s,[c('8'),c('8')],[c('10'),c('7')],[c('K'),c('3')]);assert.ok(s.split());assert.equal(s.hand.hands.length,2);assert.equal(s.balance,80);s.stand();assert.equal(s.hand.active,1);s.stand();assert.equal(s.balance,100);assert.equal(s.hand.status,'finished');const a=session();fixed(a,[c('A'),c('A')],[c('10'),c('8')],[c('K'),c('Q')]);a.split();assert.equal(a.hand.status,'finished');assert.equal(a.balance,120);assert.ok(a.hand.hands.every(h=>h.cards.length===2));});
test('resplits cap at four hands, extra bets require funds, doubles take exactly one card',()=>{const s=session();fixed(s,[c('8'),c('8')],[c('10'),c('7')],Array.from({length:8},()=>c('8')));s.split();s.split();s.split();assert.equal(s.hand.hands.length,4);assert.equal(s.canSplit,false);const d=session();fixed(d,[c('5'),c('6')],[c('10'),c('7')],[c('K')]);assert.ok(d.double());assert.equal(d.hand.hands[0].cards.length,3);assert.equal(d.hand.hands[0].bet,20);assert.equal(d.balance,120);const poor=session();fixed(poor,[c('5'),c('6')],[c('10'),c('7')],[]);poor.balance=0;assert.equal(poor.double(),false);});
test('insurance is offered before peek, pays 2:1, and late surrender loses half the main wager',()=>{const s=session();fixed(s,[c('9'),c('7')],[c('A'),c('K')],[]);s.hand.status='insurance';s.insurance(true);assert.equal(s.balance,100);assert.equal(s.hand.status,'finished');const a=session();fixed(a,[c('9'),c('7')],[c('A'),c('6')],[]);a.hand.status='insurance';a.insurance(false);assert.ok(a.canSurrender);a.surrender();assert.equal(a.balance,95);const b=session();fixed(b,[c('8'),c('8')],[c('10'),c('7')],[c('4'),c('3')]);b.split();assert.equal(b.canSurrender,false);});
test('draw poker evaluates wheels, royal flushes, pairs, full houses and blocks double draw',()=>{assert.equal(pokerResult(['A','2','3','4','5'].map(c=>({rank:c,suit:'♥'}))).name,'Straight flush');assert.equal(pokerResult(['10','J','Q','K','A'].map(c=>({rank:c,suit:'♥'}))).multiplier,800);assert.equal(pokerResult([c('J'),c('J','♥'),c('2'),c('5'),c('9')]).multiplier,1);assert.equal(pokerResult([c('3'),c('3','♥'),c('3','♦'),c('A'),c('A','♥')]).multiplier,9);const s=session();s.dealPoker(10);assert.throws(()=>s.spin(10),/Finish/);s.drawPoker([0,1,2,3,4]);const balance=s.balance;assert.equal(s.drawPoker([]),false);assert.equal(s.balance,balance);});
test('European roulette zero loses outside bets and straight-up zero pays 35:1 plus stake',()=>{const s=session(()=>0);assert.equal(s.roulette(10,'red').payout,0);assert.equal(s.balance,90);assert.equal(s.roulette(10,'0').payout,360);assert.equal(s.balance,440);});
