import test from 'node:test';import assert from 'node:assert/strict';
import {BRIDGE_SPANS} from '../src/bridges.js';
import {bridgeAt,physicalWaterAt,updateBridgeContact,startBridgeJump,riverCurrent} from '../src/river-travel.js';
import {startJump,updateJump} from '../src/controls.js';
const b=BRIDGE_SPANS[0],point=(along,across=0)=>({x:b.x+Math.cos(b.angle)*along-Math.sin(b.angle)*across,y:b.y+Math.sin(b.angle)*along+Math.cos(b.angle)*across});
test('water remains under the bridge and swimmers are not automatically promoted to the deck',()=>{const p={...point(b.length/2),layer:'surface',swimming:true};assert.ok(physicalWaterAt(p.x,p.y));assert.equal(bridgeAt(p.x,p.y),b);updateBridgeContact(p,p.x-Math.sin(b.angle)*90,p.y+Math.cos(b.angle)*90);assert.equal(p.bridgeId,undefined);});
test('land entry and a deliberate jump mount the bridge, leaving its edge drops into water',()=>{const land=point(-70),p={...point(0),layer:'surface'};assert.equal(physicalWaterAt(land.x,land.y),false);updateBridgeContact(p,land.x,land.y);assert.equal(p.bridgeId,b.path);Object.assign(p,point(b.length/2));updateBridgeContact(p);assert.equal(p.bridgeId,b.path);Object.assign(p,point(b.length/2,85));updateBridgeContact(p);assert.equal(p.bridgeId,null);p.swimming=true;assert.ok(startBridgeJump(p,startJump));updateJump(p,.18);Object.assign(p,point(b.length/2));updateBridgeContact(p);assert.equal(p.bridgeId,b.path);});
test('bridge jump is restricted to nearby surface bridges; river flow follows downstream and excludes land',()=>{const p={x:10000,y:8000,layer:'surface',swimming:true};assert.equal(startBridgeJump(p,startJump),false);const center=point(b.length/2),flow=riverCurrent(center.x,center.y);assert.ok(Math.hypot(flow.dx,flow.dy)>20);assert.ok(flow.dy>0);assert.deepEqual(riverCurrent(100,100),{dx:0,dy:0});const submerged={...center,layer:'ocean',swimming:true,underwater:true};assert.equal(startBridgeJump(submerged,startJump),false);});

test('every rotated bridge retains deck contact along its rails and tolerates small edge overshoot',()=>{for(const span of BRIDGE_SPANS){const at=(along,across)=>({x:span.x+Math.cos(span.angle)*along-Math.sin(span.angle)*across,y:span.y+Math.sin(span.angle)*along+Math.cos(span.angle)*across});for(const side of [-1,1]){const p={...at(span.length/2,side*57),layer:'surface',bridgeId:span.path};assert.equal(bridgeAt(p.x,p.y),span);updateBridgeContact(p);assert.equal(p.bridgeId,span.path);Object.assign(p,at(span.length/2,side*73));updateBridgeContact(p);assert.equal(p.bridgeId,span.path);Object.assign(p,at(span.length/2,side*86));updateBridgeContact(p);assert.equal(p.bridgeId,null);}const swimmer={...at(span.length/2,60),layer:'surface',swimming:true};updateBridgeContact(swimmer);assert.equal(swimmer.bridgeId,undefined);}});
