import test from 'node:test';
import assert from 'node:assert/strict';
import {Inventory,RECIPES} from '../src/crafting.js';
import {evolveBow,BOW_FORMS,nextBowForm} from '../src/bow-upgrades.js';
import {tradeResource,HouseLoot} from '../src/town-services.js';
import {TOWN_BUILDINGS,PORTALS,DESCENTS,LAYERS,randomSurfaceSpawn,portalDirection,canWalk} from '../src/world.js';
import {CreatureRegistry,populateCreatures} from '../src/creatures.js';
import {itemSvg} from '../src/item-art.js';

test('ordinary coins come from sales and house loot contains saleable supplies',()=>{const inv=new Inventory();assert.equal(inv.coins,0);inv.add('fang',3);assert.ok(tradeResource(inv,'fang',1,false).ok);assert.equal(inv.coins,9);const h=new HouseLoot(()=>.3);h.collect('test',0,inv);assert.equal(inv.coins,9);assert.ok(Object.values(inv.resources).some(n=>n>0));});
test('bow evolution consumes increasing materials, keeps one inventory item, and improves damage and timing',()=>{const inv=new Inventory({level:20});for(const r of Object.keys(inv.resources))inv.resources[r]=1000;inv.craft('wood-bow');inv.equip('wood-bow');const item=inv.equippedTool;for(let level=1;level<BOW_FORMS.length;level++){const next=nextBowForm(item),before={...inv.resources},damage=item.damage;assert.ok(evolveBow(inv,'wood-bow').ok);assert.equal(inv.equippedTool,item);assert.equal(inv.owned.size,1);assert.equal(item.name,next.name);assert.ok(item.damage>damage);for(const [r,n] of Object.entries(next.cost))assert.equal(inv.resources[r],before[r]-n);}assert.equal(evolveBow(inv,'wood-bow').ok,false);assert.equal(inv.coins,0);});
test('bow upgrades reject missing materials or levels without spending anything',()=>{const inv=new Inventory();inv.add('wood',20);inv.add('sticks',3);inv.add('leaves',3);inv.craft('wood-bow');assert.equal(evolveBow(inv,'wood-bow').ok,false);inv.add('hide',2);assert.ok(evolveBow(inv,'wood-bow').ok);for(const r of Object.keys(inv.resources))inv.resources[r]=100;const before={...inv.resources};assert.equal(evolveBow(inv,'wood-bow').ok,false);assert.deepEqual(inv.resources,before);});
test('higher-tier swords cost more and outdamage clubs; spear reach and hammer knockback differ',()=>{for(const club of RECIPES.filter(r=>r.type==='club'&&r.depth>=2)){const sword=RECIPES.find(r=>r.tier===club.tier&&r.type==='sword'),spear=RECIPES.find(r=>r.tier===club.tier&&r.type==='spear'),hammer=RECIPES.find(r=>r.tier===club.tier&&r.type==='warhammer');assert.ok(sword.damage>club.damage);assert.ok(sword.cost[club.tier]>club.cost[club.tier]);assert.ok(spear.range>sword.range);assert.ok(hammer.knockback>sword.knockback);for(const r of [sword,spear,hammer])assert.ok(itemSvg(r).includes('<path'));}});
test('buildings have a gap across their complete rendered silhouettes',()=>{for(let i=0;i<TOWN_BUILDINGS.length;i++)for(let j=i+1;j<TOWN_BUILDINGS.length;j++){const a=TOWN_BUILDINGS[i],b=TOWN_BUILDINGS[j];assert.ok(Math.abs(a.x-b.x)>500||Math.abs(a.y-b.y)>470,`${a.id} touches ${b.id}`);}});
test('random starting positions are safe, vary by random input, and stay near inhabited towns',()=>{const results=[];let seed=12;const rng=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<50;i++){const p=randomSurfaceSpawn(rng);assert.ok(canWalk(p.x,p.y,'surface',80));results.push(`${p.x},${p.y}`);}assert.ok(new Set(results).size>40);});
test('all cave mouths match surface coordinates and every descent has aligned ends and clear direction labels',()=>{for(const p of PORTALS)assert.deepEqual(p.cave,p.surface);for(const p of DESCENTS){const layers=['surface','cave','deep','abyss','core','mantle','vault','seven-eleven'].filter(l=>p[l]);assert.equal(layers.length,2);if(p['seven-eleven']){for(const l of layers)assert.ok(canWalk(p[l].x,p[l].y,l));}else assert.deepEqual(p[layers[0]],p[layers[1]]);assert.equal(portalDirection(p,layers[0]),'Descend');assert.equal(portalDirection(p,layers[1]),'Ascend');}});
test('cave species vary by depth and all added drop resources exist in the inventory',()=>{const registry=new CreatureRegistry();populateCreatures(registry);const inv=new Inventory();for(const c of registry.creatures)for(const id of Object.keys(c.loot))assert.ok(id in inv.resources,id);for(const kind of ['caveSpider','rootStalker','frostSerpent','duneBurrower','bogSpitter','obsidianSentinel','crystalMoth','voidReaper','magmaBrute'])assert.ok(registry.creatures.some(c=>c.kind===kind),kind);const sets=['cave','deep','abyss','core'].map(l=>new Set(registry.creatures.filter(c=>c.layer===l).map(c=>c.kind)));assert.ok(!sets[0].has('voidReaper'));assert.ok(sets[2].has('voidReaper'));assert.ok(sets[3].has('magmaBrute'));});
