import {GARDEN_RESOURCES} from './gardening.js';
export const FRONTIER_RESOURCES={
 ...GARDEN_RESOURCES,
 steezusBook:["Steezus’s Book",'Craft at player level 5, or win an underground scratch ticket','A sulfur-bound boss relic. Crafted from one Old Testament and seven Sulfur. Only Darren buys it.','▣'],
 scratchTicket:['Scratch Ticket','Underground 7-Eleven lottery machine · layer 7','Costs 25 coins. Scratch to win coins, dried marijuana or Steezus’s Book.','▤'],
 sulfur:['Sulfur Ore','Outcrops around Steezus on Cloudspine','Mine with a pickaxe. Reserved for future crafting.','◆'],
 oldTestament:['Old Testament','Defeat Steezus','Craft Steezus’s Book at level 5, or sell to Darren.','▣'],
 rawMarijuana:['Fresh Marijuana','Sparse clustered plants on mountain plateaus','Dry one plant harvest for 30 seconds in a fueled drying shack.','✿'],
 driedMarijuana:['Dried Marijuana','Drying shack','Use for +50% maximum health and +50% XP for 60 seconds. Refreshes duration; does not stack.','✿'],
 alpineFiber:['Alpine Fiber','Mountain plateau tufts','Glider cloth, climbing equipment, and advanced fishing lines.','⌁'],
 skyCrystal:['Sky Crystal','Mountain summit crystals','High-altitude power source for technical tools and buildings.','✦'],
 eagleFeather:['Eagle Feather','Summit nests and Bigfoot','Lightweight transport and quest material.','⌁'],
 bigfootFur:['Bigfoot Fur','Defeat a mountain Bigfoot','Boss trophy and reinforced clothing.','▣'],
 pearl:['Pearl','Ocean floor shells and treasure','Fishing quests and diving equipment.','◉'],
 coral:['Coral','Ocean floor outcrops','Breathing armor and sea crafting.','✧'],
 seaScale:['Sea Scale','Ocean wildlife','Rafts and aquatic equipment.','◇'],
 seaEssence:['Sea Essence','Deep ocean predators and treasure','The fisherman’s final trial and technical equipment.','✦'],
 sunkenRelic:['Sunken Relic','Deep ocean treasure chests','Final fisherman quest offering.','▣'],
};
export const FRONTIER_RECIPES=[
 {id:'steezusBook',name:'Steezus’s Book',category:'resource',tier:'sulfur',level:5,station:1,cost:{oldTestament:1,sulfur:7},detail:'A sulfur-bound boss relic. Requires player level 5 and a Bark Workbench. Only Darren buys this book.'},
 {id:'waterskin',name:'Waterskin',category:'tool',type:'waterskin',tier:'wood',level:1,cost:{hide:2,leaves:4},detail:'Select and click nearby water to fill water for your plant boxes (holds 12 units).'},
 {id:'reef-rod',name:'Reef Rod',category:'tool',type:'rod',tier:'iron',damage:3,level:3,cost:{wood:8,iron:6,sinew:4,coral:3},detail:'Reinforced line unlocks larger sea catches.'},
 {id:'abyss-rod',name:'Abyss Rod',category:'tool',type:'rod',tier:'moonstone',damage:5,level:6,cost:{moonstone:8,alpineFiber:6,skyCrystal:3,pearl:4},detail:'Deep-water line for the largest and most valuable fish.'},
 {id:'tidekeeper-armor',name:'Tidekeeper Armor',category:'gear',slot:'body',tier:'iron',defense:22,questOnly:true,level:1,cost:{},detail:'Fisherman quest 10 reward. Breathe underwater indefinitely while equipped.'},
 {id:'summit-armor',name:'Summit Ranger Armor',category:'gear',slot:'body',tier:'stone',defense:18,level:7,cost:{bigfootFur:5,skyCrystal:4,alpineFiber:8},detail:'Bigfoot fur and summit fibers reinforce this expedition armor.'},
 {id:'diver-wrap',name:'Diver Wrap',category:'gear',slot:'body',tier:'wood',defense:7,level:2,cost:{hide:8,shell:8,coral:3},detail:'Doubles the normal diving breath reserve.'},
 {id:'wood-scooter',name:'Woodland Scooter',category:'tool',type:'transport',tier:'wood',damage:0,level:2,cost:{wood:16,iron:4,hide:3},detail:'Select on the hotbar for 1.8× land travel. Cannot climb mountain slopes.'},
 {id:'reed-raft',name:'Reed Raft',category:'structure',tier:'wood',level:2,cost:{wood:18,leaves:12,sinew:4},detail:'Place only in water. E at the marked driver seat to steer; E again to stop and fish from the deck.'},
 {id:'crystal-glider',name:'Crystal Glider',category:'tool',type:'transport',tier:'moonstone',damage:0,level:6,cost:{alpineFiber:12,eagleFeather:6,skyCrystal:5,wood:12},detail:'5× flight speed with elevated flight and a downhill boost.'},
 {id:'grappling-tool',name:'Climbing Grapple',category:'tool',type:'grapple',tier:'iron',damage:0,level:4,cost:{iron:10,sinew:8,alpineFiber:4},detail:'Click nearby ground to pull yourself along a clear route. Walls still block the rope.'},
 {id:'powered-drill',name:'Crystal Drill',category:'tool',type:'pickaxe',tier:'adamantite',power:22,yield:28,damage:24,level:9,cost:{adamantite:8,cobalt:8,skyCrystal:6,essence:4},detail:'A geared crystal motor cuts ore much faster than ordinary pickaxes.'},
 ...[
 ['plant-box','Plant Box',{wood:10,stone:4,leaves:4},1,'Plant a seed and add fresh water. Grow twelve varieties of biome crops, including desert fruit, rice, frost berries, mushrooms and marijuana. Harvest returns seeds.'],
 ['drying-shack','Drying Shack',{wood:20,stone:10,leaves:12},3,'Load fresh marijuana and wood; dries each unit in 30 seconds.'],
 ['wood-floor','Wood Foundation',{wood:4},1,'A flat base floor. Snap adjacent pieces into a platform.'],
 ['wood-wall','Wood Wall',{wood:6},1,'Wooden base wall. R rotates. Destroy with an axe.'],
 ['wood-roof','Wood Roof',{wood:6,leaves:4},1,'A roof that fades when you stand underneath. Recover with an axe.'],
 ['stone-wall','Stone Wall',{stone:8,wood:2},2,'Solid base wall. R rotates before placement.'],
 ['wood-gate','Wood Gate',{wood:8,iron:2},2,'Open or close with E. Only a closed gate blocks movement.'],
 ['storage-chest','Storage Chest',{wood:10,iron:2},2,'Store resources in your base and withdraw them later.'],
 ['fish-trap','Baited Fish Trap',{wood:10,sinew:4,iron:2},3,'Place in shallow water. Each leaf bait catches one fish every 45 seconds.'],
 ['ore-extractor','Ore Extractor',{iron:16,cobalt:6,skyCrystal:3},6,'Place near cave ore. Fuel with wood; uses your best pickaxe and the actual deposit.'],
 ['timber-rig','Timber Rig',{wood:18,iron:10,sinew:5},4,'Place near a tree. Fuel with wood; uses your best crafted axe on that tree.'],
 ['healing-totem','Restoration Totem',{essence:6,skyCrystal:3,wood:10},5,'Fuel with essence. Restores nearby health; useful in caves.'],
 ].map(([id,name,cost,level,detail])=>({id,name,cost,level,detail,category:'structure',tier:level>=5?'iron':'wood'})),
];
export const TRANSPORT={
 'wood-scooter':{land:1.8,water:.4},'crystal-glider':{land:5,water:5,glider:true},
};
