import {DARREN_ONLY,STORE_LAYER,LOTTERY_SPOT} from './underground-store-data.js';
import {DARREN_PRICES,sellToDarren,buyScratch,claimScratch} from './underground-store.js';
import {resourceName} from './item-index.js';
const $=id=>document.getElementById(id);
export class StoreUI{
 constructor({inventory,player,openModal,onChange}){
  Object.assign(this,{inventory,player,openModal,onChange});this.npc=null;this.cells=new Set();this.dragging=false;
  $('darrenResource').innerHTML=DARREN_ONLY.filter(id=>!['rawMarijuana','driedMarijuana'].includes(id)).map(id=>`<option value="${id}">${resourceName(id)}</option>`).join('');$('darrenResource').onchange=()=>this.renderDarren(this.npc);
  for(const amount of [1,5])$('darrenSell'+amount).onclick=()=>{if(!this.nearDarren())return;const result=sellToDarren(this.inventory,$('darrenResource').value,amount);$('questFeedback').textContent=result.message;this.onChange();this.renderDarren(this.npc);};
  $('buyScratch').onclick=()=>{if(!this.nearLottery())return;const result=buyScratch(this.inventory);$('scratchFeedback').textContent=result.message;if(result.ok){this.ticket=this.inventory.pendingScratch;this.paint();}this.onChange();this.renderLottery();};
  const canvas=$('scratchCanvas');canvas.onpointerdown=e=>{if(!this.nearLottery()||!this.inventory.pendingScratch||e.button!==0)return;this.dragging=true;canvas.setPointerCapture(e.pointerId);this.scratch(e);};canvas.onpointermove=e=>{if(this.dragging)this.scratch(e);};canvas.onpointerup=canvas.onpointercancel=()=>this.dragging=false;
 }
 nearDarren(){return this.npc?.role==='darren'&&this.player.layer===STORE_LAYER&&Math.hypot(this.player.x-this.npc.x,this.player.y-this.npc.y)<180;}
 renderDarren(npc){this.npc=npc;const visible=npc?.role==='darren';$('darrenShop').classList.toggle('hidden',!visible);if(!visible)return;const id=$('darrenResource').value;const near=this.nearDarren();$('darrenStock').textContent=`${this.inventory.coins} coins · ${this.inventory.resources[id]} carried · ${DARREN_PRICES[id]} coins each`;for(const n of [1,5])$('darrenSell'+n).disabled=!near||this.inventory.resources[id]<n;}
 nearLottery(){return this.player.layer===STORE_LAYER&&Math.hypot(this.player.x-LOTTERY_SPOT.x,this.player.y-LOTTERY_SPOT.y)<180;}
 showLottery(){if(!this.nearLottery())return;this.openModal('lotteryModal');if(this.ticket!==this.inventory.pendingScratch){this.ticket=this.inventory.pendingScratch;this.paint();}this.renderLottery();}
 renderLottery(){const inv=this.inventory;$('lotteryCoins').textContent=`${inv.coins} coins · Tickets cost 25 coins`;$('buyScratch').disabled=!this.nearLottery()||!!inv.pendingScratch||inv.coins<25;$('scratchOdds').textContent='3% book · 15% marijuana · 42% coins · 40% no prize. Coin prizes: 20, 40, 75 or 150. Marijuana prizes: 1–3 dried.';if(!inv.pendingScratch&&!this.result)$('scratchFeedback').textContent='Buy a ticket, then rub the silver panel with your mouse or finger.';}
 paint(){const canvas=$('scratchCanvas'),c=canvas.getContext('2d');this.cells.clear();this.result=null;c.globalCompositeOperation='source-over';c.clearRect(0,0,canvas.width,canvas.height);if(!this.ticket)return;c.fillStyle='#a6aaa0';c.fillRect(0,0,canvas.width,canvas.height);for(let y=0;y<canvas.height;y+=12)for(let x=0;x<canvas.width;x+=12){c.fillStyle=(x+y)%24?'#bfc5b7':'#939d95';c.fillRect(x,y,10,10);}c.font='22px EmberRunes,monospace';c.textAlign='center';c.fillStyle='#4a5b50';c.fillText('SCRATCH HERE',canvas.width/2,canvas.height/2+7);$('scratchPrize').textContent='?';}
 scratch(e){if(!this.nearLottery()||!this.inventory.pendingScratch)return;const canvas=$('scratchCanvas'),r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height,c=canvas.getContext('2d');c.globalCompositeOperation='destination-out';c.beginPath();c.arc(x,y,23,0,Math.PI*2);c.fill();for(let row=0;row<10;row++)for(let col=0;col<20;col++)if(Math.hypot((col+.5)*canvas.width/20-x,(row+.5)*canvas.height/10-y)<23)this.cells.add(row*20+col);if(this.cells.size>=70&&this.inventory.pendingScratch){const result=claimScratch(this.inventory);this.result=result;c.clearRect(0,0,canvas.width,canvas.height);$('scratchPrize').textContent=result.message;$('scratchFeedback').textContent=result.message;this.onChange();this.renderLottery();}}
 update(){if(!$('lotteryModal').classList.contains('hidden'))this.renderLottery();}
}
